### ISSUE TITLE
Seed 0.7.0

### ISSUE THREAD

**Issue by MartinKavik** [seed-rs/seed#436]
Blockers / required tasks:
- [x] WebSocket wrapper (https://github.com/seed-rs/seed/pull/442, @MartinKavik)
- [ ] ~~Url/Routing API improvements (https://github.com/seed-rs/seed/issues/433, @power-fungus)~~ (no response, no PR => won't be included in this release)
- [x] Update / check / refactor all examples in this repo (@MartinKavik)
- [x] [Release checklist](https://github.com/seed-rs/seed/blob/master/RELEASE_CHECKLIST.md) (without [seed-rs.org](https://seed-rs.org/) content update and quickstarts update) (@MartinKavik + @David-OConnor)

After the release:
- [x] Update quickstarts (@MartinKavik)
- [x] Add Seed version switcher to [seed-rs.org](https://seed-rs.org/) (@MartinKavik)
- [ ] Write guides for Seed 0.7.0 (@MartinKavik + contributors)
- [ ] Write announcements & notify authors of related projects & write "marketing" articles (reddit, maybe Rust newsletter, etc.) (@MartinKavik + contributors)
- [ ] Add [example](https://github.com/seed-rs/seed/issues/385#issuecomment-620796508) for performance testing (@MartinKavik + @initcrash)
- [ ] Update non-keyed benchmark and add keyed benchmark - [js-framework-benchmark](https://github.com/krausest/js-framework-benchmark) (@akhilman (?) + @MartinKavik)
- [ ] Write [section](https://github.com/seed-rs/seed/issues/324#issuecomment-623050582) on performance to README and  [seed-rs.org](https://seed-rs.org/) (@MartinKavik + contributors)

---

Something is missing? Write a comment here or on the chat, thanks!

**Comment by MartinKavik** [comment]
# Release Checklist

This is a list of steps to complete when making a new release.

- [x] 1. Review the commit and PR history since last release. Ensure that all relevant
changes are included in `CHANGELOG.md`, and that breaking changes
are specifically annotated
- [x] 2. Update the version of seed dependency in the readme.
- [x] 3. Ensure both the readme and homepage website reflect API changes. Instructions
for updating the homepage are available [here](https://github.com/seed-rs/seed-homepage) [**homepage will be updated after the release**] 
- [x] 4. Update the homepage with the new release version (main page) [**homepage will be updated after the release**] , and changelog
- [x] 5.  Ensure the [quickstart repo](https://github.com/seed-rs/seed-quickstart) is updated
to reflect API changes, and the new version [**quickstarts will be updated after the release**]
- [x] 6.  Ensure the version listed in `Cargo.toml` is updated
- [x] 7. Update Rust tools: `rustup update`
- [x] 8. Run `cargo make populate_all` to synchronize `St`, `At` and other enums with official values
- [x] 9.  Run `cargo make verify` to ensure tests pass, and `clippy` / `fmt` are run
- [x] 10.  Commit and push the repo
- [x] 11.  Check that CI pipeline passed
- [ ] 12.  Run `cargo package`
- [ ] 13.  Run `cargo publish`
- [ ] 14.  Add a release on [Github](https://github.com/seed-rs/seed/releases), following the format of previous releases
- [ ] 15.  Verify the [docs page](https://docs.rs/seed/) updated correctly
- [x] 16.  Clone the quickstart repo, and verify it builds and runs correctly [**quickstarts will be updated after the release**]

---

- Updated checklist - PR https://github.com/seed-rs/seed/pull/445.
- @David-OConnor - I don't have permissions for remaining tasks - it's all yours, thanks :)

**Comment by David-OConnor** [comment]
Done

**Comment by Ben-PH** [comment]
I suggest we open a new issue titled "Seed 0.7.0 post-release" and close this one.

**Comment by MartinKavik** [comment]
@Ben-PH I don't want to spam repo watchers with unnecessary notifications (like this my comment) and lose context in the new issue. Also subscribers in this issue and people landing here will have to jump to another issue to know about further progress. And there are only a few comments - it's pretty manageable.

**Comment by MartinKavik** [comment]
UPDATE: Both quickstarts updated and refactored.

**Comment by svenstaro** [comment]
This can be closed as the release has long been made. :)
